### ISSUE TITLE
Crash whenever I compile the homebrew

### ISSUE THREAD

**Issue by Ch0wW** [fgsfdsfgs/nxquake2#1]
Using Atmosphere 0.8.4.

Devkitpro is at the latest version.

Whenever I compile and try to run the homebrew, it immediately crashes to a fatal error.

**Comment by fgsfdsfgs** [comment]
This has not been updated for use with latest libnx, which has some potentially breaking gfx changes. In fact all of my ports are probably broken.

**Comment by fgsfdsfgs** [comment]
In fact it would probably help if you attached the Atmosphere crash log it produces and/or `/switch/nxquake2/crash.log` if there's any.

**Comment by Ch0wW** [comment]
Actually, I just managed to fix the issue for the fatal error given from Atmosphere, and Q2 is now running fine.

I'll make a quick PR, and do the same for QuakespasmNX.

**Comment by Ch0wW** [comment]
Pull request #2 is now there.

**Comment by fgsfdsfgs** [comment]
Thanks, accepted. Everything seems to work.
