### ISSUE TITLE
New build issue on Switch

### ISSUE THREAD

**Issue by mrdude2478** [fgsfdsfgs/nxquake2#6]
Compiles fine from the git - however gives the following error in a crash log:

Error: No usable renderer found!

While game starts, exits straight away and produces the crash log.

**Comment by fgsfdsfgs** [comment]
Remove your old config or set r_mode to 0 in it.

**Comment by mrdude2478** [comment]
Thanks, I changed r mode to 0 - now the game runs but using left/right joystick is very slow. I then removed the config and now the game fails to load. Can you post your config file please.

**Comment by mrdude2478** [comment]
I've removed this from the config:

set joy_axis_leftx "sidemove"
set joy_axis_leftx_threshold "0.25"
set joy_axis_lefty "forwardmove"
set joy_axis_lefty_threshold "0.25"
set joy_axis_rightx "yaw"
set joy_axis_rightx_threshold "0.25"
set joy_axis_righty "pitch"
set joy_axis_righty_threshold "0.25"
set joy_axis_triggerleft "triggerleft"
set joy_axis_triggerleft_threshold "0.25"
set joy_axis_triggerright "triggerright"
set joy_axis_triggerright_threshold "0.25"
set joy_forwardsensitivity "1.0"
set joy_haptic_magnitude "0.0"
set joy_pitchsensitivity "1.0"
set joy_sidesensitivity "1.0"
set joy_upsensitivity "1.0"
set joy_yawsensitivity "1.0"

Now the left/right is working - still, if you remove the config file - the game will crash and a new config will not be generated.

**Comment by fgsfdsfgs** [comment]
This is not ready for release yet. You can also take the config from the previous release.

**Comment by fgsfdsfgs** [comment]
Fixed in 0a5e935.

**Comment by mrdude2478** [comment]
Thanks, Also I found an issue where some game saves would load, others wouldn't - want me to upload my save file so you can see?

Error in console shows - name is longer than buffer (2048 chars).

**Comment by fgsfdsfgs** [comment]
`mmove name` or `function name`?

**Comment by mrdude2478** [comment]
I deleted that save, tried all the others and the game is saving fine. Sorry about the previous. I've reconfigured my config file to bind some extra buttons - now everything is working great with no issues. Thanks.

**Comment by fgsfdsfgs** [comment]
Alright, be aware that new releases might break save compatibility.
