### ISSUE TITLE
Nintendo Switch makefile missing

### ISSUE THREAD

**Issue by mrdude2478** [fgsfdsfgs/nxquake2#9]
Please can you attach the makefile for Nintendo switch as the current one is not for the switch.

**Comment by fgsfdsfgs** [comment]
Use CMake and follow [the build instructions](https://github.com/fgsfdsfgs/nxquake2/blob/switch/doc/990_switch.md).

**Comment by mrdude2478** [comment]
Thanks, I was looking in the readme. I didn't notice that there would be build examples in the docs - doh!

I am still having issues building though, apparenty cmake is telling me I don't have OPENSSL installed - but I do! This is my error:

-- Found OpenGL: /opt/devkitpro/portlibs/switch/lib/libEGL.a
-- Looking for backtrace
-- Looking for backtrace - not found
-- Looking for backtrace in execinfo
-- Looking for backtrace in execinfo - not found
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  suitable version "3.1.0", minimum required is "3")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindOpenSSL.cmake:670 (find_package_handle_standard_args)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/local/lib/cmake/CURL/CURLConfig.cmake:52 (find_dependency)
  CMakeLists.txt:251 (find_package)

**Comment by fgsfdsfgs** [comment]
This seems to be coming from your libcurl install. Make sure you have `switch-mbedtls` and `switch-curl` installed.

**Comment by mrdude2478** [comment]
@fgsfdsfgs 

Thanks, i had those installed, but I had a rouge curl installed. I manually removed that and then rebooted my laptop and everything built well, the game + all the addons.
